/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Orval Null in Enum Problem
 * OpenAPI spec version: 1.0.0
 */
export type Foo = typeof Foo[keyof typeof Foo];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Foo = {
  '': ,
} as const;

