/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Orval Null in Enum Problem
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Foo
} from './foo.schemas'



  export const getFoo = <TData = AxiosResponse<Foo>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/foo`,options
    );
  }

export type GetFooResult = AxiosResponse<Foo>
