/**
 * Generated by orval v6.11.0-alpha.8 🍺
 * Do not edit manually.
 * Orval Null in Enum Problem
 * OpenAPI spec version: 1.0.0
 */
export type Foo = typeof Foo[keyof typeof Foo];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Foo = {
  NUMBER_1: 1,
  '': ,
} as const;

